# Generated by Django 5.0.2 on 2024-03-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_agent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organizor',
            field=models.BooleanField(default=True),
        ),
    ]
