# Generated by Django 5.0.2 on 2024-03-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='organization',
        ),
    ]
